// 하드코딩 데이터
export const MOCK_RESERVATIONS = [
  {
    id: 1,
    petId: 1,
    academyId: 1,
    petName: "지동이",
    petBreed: "보더콜리",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "MALE" as const,
  },
  {
    id: 2,
    petId: 2,
    academyId: 1,
    petName: "초코",
    petBreed: "푸들",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "FEMALE" as const,
  },
  {
    id: 3,
    petId: 3,
    academyId: 1,
    petName: "말포이",
    petBreed: "셔틀랜드 쉽독",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "MALE" as const,
  },
  {
    id: 4,
    petId: 4,
    academyId: 1,
    petName: "어쭈",
    petBreed: "말티푸",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "FEMALE" as const,
  },
  {
    id: 5,
    petId: 5,
    academyId: 1,
    petName: "배추",
    petBreed: "푸들",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "FEMALE" as const,
  },
  {
    id: 6,
    petId: 6,
    academyId: 1,
    petName: "뽀삐",
    petBreed: "말티즈",
    academyName: "왈 유치원",
    reservationDate: "20250908",
    reservationStatus: "RESERVED",
    petImage: null,
    gender: "MALE" as const,
  },
];
